# Code generated by xfx; DO NOT EDIT.

APP_NAME=magic-box
.PHONY: gen
gen:
	bash ./scripts/gen.sh && bash ./scripts/i18n_pull.sh ${branch}
.PHONY: genmock
genmock:
	bash ./scripts/genmock.sh
.PHONY: checklint
checklint:
	bash ./scripts/checklint.sh
.PHONY: checklintall
checklintall:
	bash ./scripts/checklintall.sh
# 将项目升级至最新版
.PHONY: upgrade
upgrade:
	GOARCH='' go install ksogit.kingsoft.net/o/stage/v2@latest && stage gen && make gen
# 更新 SDK 版本
# 示例：make pullspec revision=beta
.PHONY: pullspec
pullspec:
	stage pullspec --revision=${revision}
