#!/bin/bash
# Code generated by xfx; DO NOT EDIT.

APPNAME="MAGIC_BOX"

##################################################
## 安全加解密相关预设变量
##################################################
if [ "$KMS_KEY_ID" ]; then
    export ENCS_KMS_KEY_ID=$KMS_KEY_ID
fi
export ENCS_KMS_LOCAL_ENABLED="${ENCS_KMS_LOCAL_ENABLED}"
export ENCS_KMS_KEY_CONFIG_PATH="${KMS_CONFIG_PATH}"
export ENCS_KMS_KEY_SECRET_PATH="${KMS_SECRET_PATH}"


