/*-----------------------------------------------------------------------------------
 * Kingsoft Office Enterprise Cloud Services.
 * Copyright (c) Kingsoft Office,  All rights reserved.
 *-----------------------------------------------------------------------------------*/
// Code generated by xfx; DO NOT EDIT.

package srv

import (
	"context"
	"html"
	"time"

	"magic-box/schemas"
)

var _ = html.EscapeString
var _ schemas.Error
var _ = time.Parse

type CreateAiRequest struct {
	schemas.CreateAiRequest
}

func NewCreateAiRequest() *CreateAiRequest {
	v := &CreateAiRequest{}
	v.CreateAiRequest = schemas.NewCreateAiRequest()
	return v
}

func (r *CreateAiRequest) EscapeStrings() {
	r.CreateAiRequest.EscapeStrings()
}

type CreateAiResponse = schemas.AiItem

var NewCreateAiResponse = schemas.NewAiItem

type CreateAiFunc func(context.Context, *CreateAiRequest) (*CreateAiResponse, error)
