/*-----------------------------------------------------------------------------------
 * Kingsoft Office Enterprise Cloud Services.
 * Copyright (c) Kingsoft Office,  All rights reserved.
 *-----------------------------------------------------------------------------------*/
// Code generated by xfx; DO NOT EDIT.

package srv

import (
	"context"
	"html"
	"time"

	"magic-box/schemas"
)

var _ = html.EscapeString
var _ schemas.Error
var _ = time.Parse

type CreateAssistantRequest struct {
	schemas.CreateAssistantRequest
}

func NewCreateAssistantRequest() *CreateAssistantRequest {
	v := &CreateAssistantRequest{}
	v.CreateAssistantRequest = schemas.NewCreateAssistantRequest()
	return v
}

func (r *CreateAssistantRequest) EscapeStrings() {
	r.CreateAssistantRequest.EscapeStrings()
}

type CreateAssistantResponse = schemas.AssistantItem

var NewCreateAssistantResponse = schemas.NewAssistantItem

type CreateAssistantFunc func(context.Context, *CreateAssistantRequest) (*CreateAssistantResponse, error)
