/*-----------------------------------------------------------------------------------
 * Kingsoft Office Enterprise Cloud Services.
 * Copyright (c) Kingsoft Office,  All rights reserved.
 *-----------------------------------------------------------------------------------*/
// Code generated by xfx; DO NOT EDIT.

package srv

import (
	"context"
	"html"
	"time"

	"magic-box/schemas"
)

var _ = html.EscapeString
var _ schemas.Error
var _ = time.Parse

type CreateKnowledgeRequest struct {
	schemas.CreateKnowledgeRequest
}

func NewCreateKnowledgeRequest() *CreateKnowledgeRequest {
	v := &CreateKnowledgeRequest{}
	v.CreateKnowledgeRequest = schemas.NewCreateKnowledgeRequest()
	return v
}

func (r *CreateKnowledgeRequest) EscapeStrings() {
	r.CreateKnowledgeRequest.EscapeStrings()
}

type CreateKnowledgeResponse = schemas.KnowledgeItem

var NewCreateKnowledgeResponse = schemas.NewKnowledgeItem

type CreateKnowledgeFunc func(context.Context, *CreateKnowledgeRequest) (*CreateKnowledgeResponse, error)
