/*-----------------------------------------------------------------------------------
 * Kingsoft Office Enterprise Cloud Services.
 * Copyright (c) Kingsoft Office,  All rights reserved.
 *-----------------------------------------------------------------------------------*/
// Code generated by xfx; DO NOT EDIT.

package srv

import (
	"context"
	"html"
	"time"

	"magic-box/schemas"
)

var _ = html.EscapeString
var _ schemas.Error
var _ = time.Parse

type CreateSolutionRequest struct {
	schemas.CreateSolutionRequest
}

func NewCreateSolutionRequest() *CreateSolutionRequest {
	v := &CreateSolutionRequest{}
	v.CreateSolutionRequest = schemas.NewCreateSolutionRequest()
	return v
}

func (r *CreateSolutionRequest) EscapeStrings() {
	r.CreateSolutionRequest.EscapeStrings()
}

type CreateSolutionResponse = schemas.SolutionItem

var NewCreateSolutionResponse = schemas.NewSolutionItem

type CreateSolutionFunc func(context.Context, *CreateSolutionRequest) (*CreateSolutionResponse, error)
