/*-----------------------------------------------------------------------------------
 * Kingsoft Office Enterprise Cloud Services.
 * Copyright (c) Kingsoft Office,  All rights reserved.
 *-----------------------------------------------------------------------------------*/
// Code generated by xfx; DO NOT EDIT.

package srv

import (
	"context"
	"html"
	"time"

	"magic-box/schemas"
)

var _ = html.EscapeString
var _ schemas.Error
var _ = time.Parse

type DeleteKnowledgeRequest struct {
	KnowledgeId string `json:"-" path:"knowledge_id,required" validate:"max=1024"`
}

func NewDeleteKnowledgeRequest() *DeleteKnowledgeRequest {
	v := &DeleteKnowledgeRequest{}
	return v
}

func (r *DeleteKnowledgeRequest) EscapeStrings() {
	r.KnowledgeId = html.EscapeString(r.KnowledgeId)
}

type DeleteKnowledgeFunc func(context.Context, *DeleteKnowledgeRequest) error
