/*-----------------------------------------------------------------------------------
 * Kingsoft Office Enterprise Cloud Services.
 * Copyright (c) Kingsoft Office,  All rights reserved.
 *-----------------------------------------------------------------------------------*/
// Code generated by xfx; DO NOT EDIT.

package srv

import (
	"context"
	"html"
	"time"

	"magic-box/schemas"
)

var _ = html.EscapeString
var _ schemas.Error
var _ = time.Parse

type DeleteSolutionRequest struct {
	SolutionId string `json:"-" path:"solution_id,required" validate:"max=1024"`
}

func NewDeleteSolutionRequest() *DeleteSolutionRequest {
	v := &DeleteSolutionRequest{}
	return v
}

func (r *DeleteSolutionRequest) EscapeStrings() {
	r.SolutionId = html.EscapeString(r.SolutionId)
}

type DeleteSolutionFunc func(context.Context, *DeleteSolutionRequest) error
