/*-----------------------------------------------------------------------------------
 * Kingsoft Office Enterprise Cloud Services.
 * Copyright (c) Kingsoft Office,  All rights reserved.
 *-----------------------------------------------------------------------------------*/
// Code generated by xfx; DO NOT EDIT.

package srv

import (
	"context"
	"html"
	"time"

	"magic-box/schemas"
)

var _ = html.EscapeString
var _ schemas.Error
var _ = time.Parse

type DeleteAssistantRequest struct {
	Id string `json:"-" path:"id,required" validate:"max=1024"`
}

func NewDeleteAssistantRequest() *DeleteAssistantRequest {
	v := &DeleteAssistantRequest{}
	return v
}

func (r *DeleteAssistantRequest) EscapeStrings() {
	r.Id = html.EscapeString(r.Id)
}

type DeleteAssistantFunc func(context.Context, *DeleteAssistantRequest) error
