/*-----------------------------------------------------------------------------------
 * Kingsoft Office Enterprise Cloud Services.
 * Copyright (c) Kingsoft Office,  All rights reserved.
 *-----------------------------------------------------------------------------------*/
// Code generated by xfx; DO NOT EDIT.

package srv

import (
	"context"
	"html"
	"time"

	"magic-box/schemas"
)

var _ = html.EscapeString
var _ schemas.Error
var _ = time.Parse

type DeleteAiRequest struct {
	AiId string `json:"-" path:"ai_id,required" validate:"max=1024"`
}

func NewDeleteAiRequest() *DeleteAiRequest {
	v := &DeleteAiRequest{}
	return v
}

func (r *DeleteAiRequest) EscapeStrings() {
	r.AiId = html.EscapeString(r.AiId)
}

type DeleteAiFunc func(context.Context, *DeleteAiRequest) error
