/*-----------------------------------------------------------------------------------
 * Kingsoft Office Enterprise Cloud Services.
 * Copyright (c) Kingsoft Office,  All rights reserved.
 *-----------------------------------------------------------------------------------*/
// Code generated by xfx; DO NOT EDIT.

package srv

import (
	"context"
	"html"
	"time"

	"magic-box/schemas"
)

var _ = html.EscapeString
var _ schemas.Error
var _ = time.Parse

type GetSolutionRequest struct {
	SolutionId string `json:"-" path:"solution_id,required" validate:"max=1024"`
}

func NewGetSolutionRequest() *GetSolutionRequest {
	v := &GetSolutionRequest{}
	return v
}

func (r *GetSolutionRequest) EscapeStrings() {
	r.SolutionId = html.EscapeString(r.SolutionId)
}

type GetSolutionResponse = schemas.SolutionItem

var NewGetSolutionResponse = schemas.NewSolutionItem

type GetSolutionFunc func(context.Context, *GetSolutionRequest) (*GetSolutionResponse, error)
