/*-----------------------------------------------------------------------------------
 * Kingsoft Office Enterprise Cloud Services.
 * Copyright (c) Kingsoft Office,  All rights reserved.
 *-----------------------------------------------------------------------------------*/
// Code generated by xfx; DO NOT EDIT.

package srv

import (
	"context"
	"html"
	"time"

	"magic-box/schemas"
)

var _ = html.EscapeString
var _ schemas.Error
var _ = time.Parse

type GetKnowledgeRequest struct {
	KnowledgeId string `json:"-" path:"knowledge_id,required" validate:"max=1024"`
}

func NewGetKnowledgeRequest() *GetKnowledgeRequest {
	v := &GetKnowledgeRequest{}
	return v
}

func (r *GetKnowledgeRequest) EscapeStrings() {
	r.KnowledgeId = html.EscapeString(r.KnowledgeId)
}

type GetKnowledgeResponse = schemas.KnowledgeItem

var NewGetKnowledgeResponse = schemas.NewKnowledgeItem

type GetKnowledgeFunc func(context.Context, *GetKnowledgeRequest) (*GetKnowledgeResponse, error)
