/*-----------------------------------------------------------------------------------
 * Kingsoft Office Enterprise Cloud Services.
 * Copyright (c) Kingsoft Office,  All rights reserved.
 *-----------------------------------------------------------------------------------*/
// Code generated by xfx; DO NOT EDIT.

package srv

import (
	"context"
	"html"
	"time"

	"magic-box/schemas"
)

var _ = html.EscapeString
var _ schemas.Error
var _ = time.Parse

type GetAssistantRequest struct {
	Id string `json:"-" path:"id,required" validate:"max=1024"`
}

func NewGetAssistantRequest() *GetAssistantRequest {
	v := &GetAssistantRequest{}
	return v
}

func (r *GetAssistantRequest) EscapeStrings() {
	r.Id = html.EscapeString(r.Id)
}

type GetAssistantResponse = schemas.AssistantItem

var NewGetAssistantResponse = schemas.NewAssistantItem

type GetAssistantFunc func(context.Context, *GetAssistantRequest) (*GetAssistantResponse, error)
