/*-----------------------------------------------------------------------------------
 * Kingsoft Office Enterprise Cloud Services.
 * Copyright (c) Kingsoft Office,  All rights reserved.
 *-----------------------------------------------------------------------------------*/
// Code generated by xfx; DO NOT EDIT.

package srv

import (
	"context"
	"html"
	"time"

	"magic-box/schemas"
)

var _ = html.EscapeString
var _ schemas.Error
var _ = time.Parse

type GetAiRequest struct {
	AiId string `json:"-" path:"ai_id,required" validate:"max=1024"`
}

func NewGetAiRequest() *GetAiRequest {
	v := &GetAiRequest{}
	return v
}

func (r *GetAiRequest) EscapeStrings() {
	r.AiId = html.EscapeString(r.AiId)
}

type GetAiResponse = schemas.AiItem

var NewGetAiResponse = schemas.NewAiItem

type GetAiFunc func(context.Context, *GetAiRequest) (*GetAiResponse, error)
