/*-----------------------------------------------------------------------------------
 * Kingsoft Office Enterprise Cloud Services.
 * Copyright (c) Kingsoft Office,  All rights reserved.
 *-----------------------------------------------------------------------------------*/
// Code generated by xfx; DO NOT EDIT.

package srv

import (
	"context"
	"html"
	"time"

	"magic-box/schemas"
)

var _ = html.EscapeString
var _ schemas.Error
var _ = time.Parse

type HealthCheckRequest struct {
}

func NewHealthCheckRequest() *HealthCheckRequest {
	v := &HealthCheckRequest{}
	return v
}

func (r *HealthCheckRequest) EscapeStrings() {
}

type HealthCheckResponse = schemas.HealthReply

var NewHealthCheckResponse = schemas.NewHealthReply

type HealthCheckFunc func(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
