/*-----------------------------------------------------------------------------------
 * Kingsoft Office Enterprise Cloud Services.
 * Copyright (c) Kingsoft Office,  All rights reserved.
 *-----------------------------------------------------------------------------------*/
// Code generated by xfx; DO NOT EDIT.

package srv

import (
	"context"
	"html"
	"time"

	"magic-box/schemas"
)

var _ = html.EscapeString
var _ schemas.Error
var _ = time.Parse

type ListAssistantsRequest struct {
}

func NewListAssistantsRequest() *ListAssistantsRequest {
	v := &ListAssistantsRequest{}
	return v
}

func (r *ListAssistantsRequest) EscapeStrings() {
}

type ListAssistantsResponse = schemas.ListAssistantsReply

var NewListAssistantsResponse = schemas.NewListAssistantsReply

type ListAssistantsFunc func(context.Context, *ListAssistantsRequest) (*ListAssistantsResponse, error)
