/*-----------------------------------------------------------------------------------
 * Kingsoft Office Enterprise Cloud Services.
 * Copyright (c) Kingsoft Office,  All rights reserved.
 *-----------------------------------------------------------------------------------*/
// Code generated by xfx; DO NOT EDIT.

package srv

import (
	"context"
	"html"
	"time"

	"magic-box/schemas"
)

var _ = html.EscapeString
var _ schemas.Error
var _ = time.Parse

type ListAisRequest struct {
}

func NewListAisRequest() *ListAisRequest {
	v := &ListAisRequest{}
	return v
}

func (r *ListAisRequest) EscapeStrings() {
}

type ListAisResponse = schemas.ListAisReply

var NewListAisResponse = schemas.NewListAisReply

type ListAisFunc func(context.Context, *ListAisRequest) (*ListAisResponse, error)
