/*-----------------------------------------------------------------------------------
 * Kingsoft Office Enterprise Cloud Services.
 * Copyright (c) Kingsoft Office,  All rights reserved.
 *-----------------------------------------------------------------------------------*/
// Code generated by xfx; DO NOT EDIT.

package srv

import (
	"context"
	"html"
	"time"

	"magic-box/schemas"
)

var _ = html.EscapeString
var _ schemas.Error
var _ = time.Parse

type ListKnowledgesRequest struct {
}

func NewListKnowledgesRequest() *ListKnowledgesRequest {
	v := &ListKnowledgesRequest{}
	return v
}

func (r *ListKnowledgesRequest) EscapeStrings() {
}

type ListKnowledgesResponse = schemas.ListKnowledgesReply

var NewListKnowledgesResponse = schemas.NewListKnowledgesReply

type ListKnowledgesFunc func(context.Context, *ListKnowledgesRequest) (*ListKnowledgesResponse, error)
