/*-----------------------------------------------------------------------------------
 * Kingsoft Office Enterprise Cloud Services.
 * Copyright (c) Kingsoft Office,  All rights reserved.
 *-----------------------------------------------------------------------------------*/
// Code generated by xfx; DO NOT EDIT.

package srv

import (
	"context"
	"html"
	"time"

	"magic-box/schemas"
)

var _ = html.EscapeString
var _ schemas.Error
var _ = time.Parse

type ListSolutionsRequest struct {
}

func NewListSolutionsRequest() *ListSolutionsRequest {
	v := &ListSolutionsRequest{}
	return v
}

func (r *ListSolutionsRequest) EscapeStrings() {
}

type ListSolutionsResponse = schemas.ListSolutionsReply

var NewListSolutionsResponse = schemas.NewListSolutionsReply

type ListSolutionsFunc func(context.Context, *ListSolutionsRequest) (*ListSolutionsResponse, error)
