/*-----------------------------------------------------------------------------------
 * Kingsoft Office Enterprise Cloud Services.
 * Copyright (c) Kingsoft Office,  All rights reserved.
 *-----------------------------------------------------------------------------------*/
// Code generated by xfx; DO NOT EDIT.

package srv

import (
	"context"
	"html"
	"time"

	"magic-box/schemas"
)

var _ = html.EscapeString
var _ schemas.Error
var _ = time.Parse

type UpdateAssistantRequest struct {
	AssistantId string `json:"-" path:"assistant_id,required" validate:"max=1024"`
	schemas.UpdateAssistantRequest
}

func NewUpdateAssistantRequest() *UpdateAssistantRequest {
	v := &UpdateAssistantRequest{}
	v.UpdateAssistantRequest = schemas.NewUpdateAssistantRequest()
	return v
}

func (r *UpdateAssistantRequest) EscapeStrings() {
	r.AssistantId = html.EscapeString(r.AssistantId)
	r.UpdateAssistantRequest.EscapeStrings()
}

type UpdateAssistantResponse = schemas.AssistantItem

var NewUpdateAssistantResponse = schemas.NewAssistantItem

type UpdateAssistantFunc func(context.Context, *UpdateAssistantRequest) (*UpdateAssistantResponse, error)
