/*-----------------------------------------------------------------------------------
 * Kingsoft Office Enterprise Cloud Services.
 * Copyright (c) Kingsoft Office,  All rights reserved.
 *-----------------------------------------------------------------------------------*/
// Code generated by xfx; DO NOT EDIT.

package srv

import (
	"context"
	"html"
	"time"

	"magic-box/schemas"
)

var _ = html.EscapeString
var _ schemas.Error
var _ = time.Parse

type UpdateSolutionRequest struct {
	SolutionId string `json:"-" path:"solution_id,required" validate:"max=1024"`
	schemas.UpdateSolutionRequest
}

func NewUpdateSolutionRequest() *UpdateSolutionRequest {
	v := &UpdateSolutionRequest{}
	v.UpdateSolutionRequest = schemas.NewUpdateSolutionRequest()
	return v
}

func (r *UpdateSolutionRequest) EscapeStrings() {
	r.SolutionId = html.EscapeString(r.SolutionId)
	r.UpdateSolutionRequest.EscapeStrings()
}

type UpdateSolutionResponse = schemas.SolutionItem

var NewUpdateSolutionResponse = schemas.NewSolutionItem

type UpdateSolutionFunc func(context.Context, *UpdateSolutionRequest) (*UpdateSolutionResponse, error)
