/*-----------------------------------------------------------------------------------
 * Kingsoft Office Enterprise Cloud Services.
 * Copyright (c) Kingsoft Office,  All rights reserved.
 *-----------------------------------------------------------------------------------*/
// Code generated by xfx; DO NOT EDIT.

package srv

import (
	"context"
	"html"
	"time"

	"magic-box/schemas"
)

var _ = html.EscapeString
var _ schemas.Error
var _ = time.Parse

type UpdateAiRequest struct {
	AiId string `json:"-" path:"ai_id,required" validate:"max=1024"`
	schemas.UpdateAiRequest
}

func NewUpdateAiRequest() *UpdateAiRequest {
	v := &UpdateAiRequest{}
	v.UpdateAiRequest = schemas.NewUpdateAiRequest()
	return v
}

func (r *UpdateAiRequest) EscapeStrings() {
	r.AiId = html.EscapeString(r.AiId)
	r.UpdateAiRequest.EscapeStrings()
}

type UpdateAiResponse = schemas.AiItem

var NewUpdateAiResponse = schemas.NewAiItem

type UpdateAiFunc func(context.Context, *UpdateAiRequest) (*UpdateAiResponse, error)
