/*-----------------------------------------------------------------------------------
 * Kingsoft Office Enterprise Cloud Services.
 * Copyright (c) Kingsoft Office,  All rights reserved.
 *-----------------------------------------------------------------------------------*/
// Code generated by xfx; DO NOT EDIT.

package srv

import (
	"context"
	"html"
	"time"

	"magic-box/schemas"
)

var _ = html.EscapeString
var _ schemas.Error
var _ = time.Parse

type UpdateKnowledgeRequest struct {
	KnowledgeId string `json:"-" path:"knowledge_id,required" validate:"max=1024"`
	schemas.UpdateKnowledgeRequest
}

func NewUpdateKnowledgeRequest() *UpdateKnowledgeRequest {
	v := &UpdateKnowledgeRequest{}
	v.UpdateKnowledgeRequest = schemas.NewUpdateKnowledgeRequest()
	return v
}

func (r *UpdateKnowledgeRequest) EscapeStrings() {
	r.KnowledgeId = html.EscapeString(r.KnowledgeId)
	r.UpdateKnowledgeRequest.EscapeStrings()
}

type UpdateKnowledgeResponse = schemas.KnowledgeItem

var NewUpdateKnowledgeResponse = schemas.NewKnowledgeItem

type UpdateKnowledgeFunc func(context.Context, *UpdateKnowledgeRequest) (*UpdateKnowledgeResponse, error)
