/*-----------------------------------------------------------------------------------
 * Kingsoft Office Enterprise Cloud Services.
 * Copyright (c) Kingsoft Office,  All rights reserved.
 *-----------------------------------------------------------------------------------*/
// Code generated by xfx; DO NOT EDIT.

package ctx

import (
	"ksogit.kingsoft.net/o/xfx"
	"ksogit.kingsoft.net/o/xfx/client"
	redis "ksogit.kingsoft.net/o/xfx/kv"
	consumer "ksogit.kingsoft.net/o/xfx/mq/consumer"
	producer "ksogit.kingsoft.net/o/xfx/mq/producer"
	"magic-box/config"
)

var _ xfx.Context
var _ client.Client
var _ redis.Redis
var _ producer.Producer
var _ consumer.Consumer

type backingServices struct {
	xfx.Context
	Config *config.Config
}

func newBackingServices(c *ModuleContext) *backingServices {
	return &backingServices{
		Context: c.AppContext.Context(c.Name()),
		Config:  config.C,
	}
}
