/*-----------------------------------------------------------------------------------
 * Kingsoft Office Enterprise Cloud Services.
 * Copyright (c) Kingsoft Office,  All rights reserved.
 *-----------------------------------------------------------------------------------*/
// Code generated by xfx; DO NOT EDIT.
package config

import (
	_ "embed"

	"ksogit.kingsoft.net/o/xfx"
)

type Config struct {
	Example string `json:"example"`
}

//go:embed config.yaml
var y string

var C = &Config{}

func init() {
	xfx.RegisterYamlConfig("magic-box", []byte(y), C)
}
