components:
  responses:
    error:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
      description: error
  schemas:
    ai_item:
      properties:
        created_at:
          description: 创建时间
          maxLength: 1024
          type: string
        description:
          description: AI描述
          maxLength: 1024
          type: string
        id:
          description: AI唯一标识
          maxLength: 1024
          type: string
        name:
          description: AI名称
          maxLength: 1024
          type: string
        updated_at:
          description: 更新时间
          maxLength: 1024
          type: string
      required:
      - id
      - name
      - description
      - created_at
      - updated_at
    assistant_item:
      properties:
        created_at:
          description: 创建时间
          maxLength: 1024
          type: string
        description:
          description: 助手描述
          maxLength: 1024
          type: string
        id:
          description: 助手唯一标识
          maxLength: 1024
          type: string
        name:
          description: 助手名称
          maxLength: 1024
          type: string
        updated_at:
          description: 更新时间
          maxLength: 1024
          type: string
      required:
      - id
      - name
      - description
      - created_at
      - updated_at
    create_ai_request:
      properties:
        description:
          description: AI描述
          maxLength: 1024
          type: string
        name:
          description: AI名称
          maxLength: 1024
          type: string
      required:
      - name
      - description
    create_assistant_request:
      properties:
        description:
          description: 助手描述
          maxLength: 1024
          type: string
        name:
          description: 助手名称
          maxLength: 1024
          type: string
      required:
      - name
      - description
    create_knowledge_request:
      properties:
        description:
          description: 知识描述
          maxLength: 1024
          type: string
        name:
          description: 知识名称
          maxLength: 1024
          type: string
      required:
      - name
      - description
    create_solution_request:
      properties:
        description:
          description: 方案描述
          maxLength: 1024
          type: string
        name:
          description: 方案名称
          maxLength: 1024
          type: string
      required:
      - name
      - description
    error:
      properties:
        code:
          $ref: '#/components/schemas/error_code'
        more:
          allOf:
          - $ref: '#/components/schemas/error'
          description: more error
          nullable: true
        msg:
          description: error message
          type: string
      required:
      - code
      - msg
    error_code:
      description: |
        errors
          * '40000002' - parameter format error
      enum:
      - 40000002
      type: integer
      x-enum:
      - CodeParamFormatError
    health_reply:
      properties:
        message:
          description: 状态说明
          maxLength: 1024
          type: string
        status:
          description: 健康状态
          maxLength: 1024
          type: string
        version:
          description: 服务版本
          maxLength: 1024
          type: string
      required:
      - status
      - message
      - version
    knowledge_item:
      properties:
        created_at:
          description: 创建时间
          maxLength: 1024
          type: string
        description:
          description: 知识描述
          maxLength: 1024
          type: string
        id:
          description: 知识唯一标识
          maxLength: 1024
          type: string
        name:
          description: 知识名称
          maxLength: 1024
          type: string
        updated_at:
          description: 更新时间
          maxLength: 1024
          type: string
      required:
      - id
      - name
      - description
      - created_at
      - updated_at
    list_ais_reply:
      properties:
        items:
          description: AI项列表
          items:
            $ref: '#/components/schemas/ai_item'
          maxItems: 1024
          type: array
        total:
          description: 总数
          format: int
          type: integer
      required:
      - items
      - total
    list_assistants_reply:
      properties:
        items:
          description: 助手项列表
          items:
            $ref: '#/components/schemas/assistant_item'
          maxItems: 1024
          type: array
        total:
          description: 总数
          format: int
          type: integer
      required:
      - items
      - total
    list_knowledges_reply:
      properties:
        items:
          description: 知识项列表
          items:
            $ref: '#/components/schemas/knowledge_item'
          maxItems: 1024
          type: array
        total:
          description: 总数
          format: int
          type: integer
      required:
      - items
      - total
    list_solutions_reply:
      properties:
        items:
          description: 方案项列表
          items:
            $ref: '#/components/schemas/solution_item'
          maxItems: 1024
          type: array
        total:
          description: 总数
          format: int
          type: integer
      required:
      - items
      - total
    solution_item:
      properties:
        created_at:
          description: 创建时间
          maxLength: 1024
          type: string
        description:
          description: 方案描述
          maxLength: 1024
          type: string
        id:
          description: 方案唯一标识
          maxLength: 1024
          type: string
        name:
          description: 方案名称
          maxLength: 1024
          type: string
        updated_at:
          description: 更新时间
          maxLength: 1024
          type: string
      required:
      - id
      - name
      - description
      - created_at
      - updated_at
    update_ai_request:
      properties:
        description:
          description: AI描述
          maxLength: 1024
          type: string
        name:
          description: AI名称
          maxLength: 1024
          type: string
      required:
      - name
      - description
    update_assistant_request:
      properties:
        description:
          description: 助手描述
          maxLength: 1024
          type: string
        name:
          description: 助手名称
          maxLength: 1024
          type: string
      required:
      - name
      - description
    update_knowledge_request:
      properties:
        description:
          description: 知识描述
          maxLength: 1024
          type: string
        name:
          description: 知识名称
          maxLength: 1024
          type: string
      required:
      - name
      - description
    update_solution_request:
      properties:
        description:
          description: 方案描述
          maxLength: 1024
          type: string
        name:
          description: 方案名称
          maxLength: 1024
          type: string
      required:
      - name
      - description
info:
  title: magic-box
  version: v1
openapi: 3.0.0
paths:
  /ais:
    get:
      description: '[magic-box] 查询AI列表'
      operationId: list_ais
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/list_ais_reply'
          description: "200"
        default:
          $ref: '#/components/responses/error'
      summary: 查询AI列表
      tags:
      - ai
    post:
      description: '[magic-box] 创建AI接口'
      operationId: create_ai
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/create_ai_request'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ai_item'
          description: "200"
        default:
          $ref: '#/components/responses/error'
      summary: 创建AI
      tags:
      - ai
  /ais/{ai_id}:
    get:
      description: '[magic-box] 查询单个AI'
      operationId: get_ai
      parameters:
      - in: path
        name: ai_id
        required: true
        schema:
          maxLength: 1024
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ai_item'
          description: "200"
        default:
          $ref: '#/components/responses/error'
      summary: 查询AI详情
      tags:
      - ai
  /ais/remove/{ai_id}:
    post:
      description: '[magic-box] 删除AI'
      operationId: delete_ai
      parameters:
      - in: path
        name: ai_id
        required: true
        schema:
          maxLength: 1024
          type: string
      responses:
        "204":
          description: "204"
        default:
          $ref: '#/components/responses/error'
      summary: 删除AI
      tags:
      - ai
  /ais/update/{ai_id}:
    post:
      description: '[magic-box] 更新AI信息'
      operationId: update_ai
      parameters:
      - in: path
        name: ai_id
        required: true
        schema:
          maxLength: 1024
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/update_ai_request'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ai_item'
          description: "200"
        default:
          $ref: '#/components/responses/error'
      summary: 更新AI
      tags:
      - ai
  /assistants:
    get:
      description: '[magic-box] 查询助手列表'
      operationId: list_assistants
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/list_assistants_reply'
          description: "200"
        default:
          $ref: '#/components/responses/error'
      summary: 查询助手列表
      tags:
      - assistant
    post:
      description: '[magic-box] 创建助手接口'
      operationId: create_assistant
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/create_assistant_request'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/assistant_item'
          description: "200"
        default:
          $ref: '#/components/responses/error'
      summary: 创建助手
      tags:
      - assistant
  /assistants/{assistant_id}:
    get:
      description: '[magic-box] 查询单个助手'
      operationId: get_assistant
      parameters:
      - in: path
        name: assistant_id
        required: true
        schema:
          maxLength: 1024
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/assistant_item'
          description: "200"
        default:
          $ref: '#/components/responses/error'
      summary: 查询助手详情
      tags:
      - assistant
  /assistants/remove/{assistant_id}:
    post:
      description: '[magic-box] 删除助手'
      operationId: delete_assistant
      parameters:
      - in: path
        name: assistant_id
        required: true
        schema:
          maxLength: 1024
          type: string
      responses:
        "204":
          description: "204"
        default:
          $ref: '#/components/responses/error'
      summary: 删除助手
      tags:
      - assistant
  /assistants/update/{assistant_id}:
    post:
      description: '[magic-box] 更新助手信息'
      operationId: update_assistant
      parameters:
      - in: path
        name: assistant_id
        required: true
        schema:
          maxLength: 1024
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/update_assistant_request'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/assistant_item'
          description: "200"
        default:
          $ref: '#/components/responses/error'
      summary: 更新助手
      tags:
      - assistant
  /health:
    get:
      description: '[magic-box] 服务健康检查接口'
      operationId: health_check
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/health_reply'
          description: "200"
        default:
          $ref: '#/components/responses/error'
      summary: 健康检查
      tags:
      - health
  /knowledges:
    get:
      description: '[magic-box] 查询知识列表'
      operationId: list_knowledges
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/list_knowledges_reply'
          description: "200"
        default:
          $ref: '#/components/responses/error'
      summary: 查询知识列表
      tags:
      - knowledge
    post:
      description: '[magic-box] 创建知识接口'
      operationId: create_knowledge
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/create_knowledge_request'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/knowledge_item'
          description: "200"
        default:
          $ref: '#/components/responses/error'
      summary: 创建知识
      tags:
      - knowledge
  /knowledges/{knowledge_id}:
    get:
      description: '[magic-box] 查询单个知识'
      operationId: get_knowledge
      parameters:
      - in: path
        name: knowledge_id
        required: true
        schema:
          maxLength: 1024
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/knowledge_item'
          description: "200"
        default:
          $ref: '#/components/responses/error'
      summary: 查询知识详情
      tags:
      - knowledge
  /knowledges/remove/{knowledge_id}:
    post:
      description: '[magic-box] 删除知识'
      operationId: delete_knowledge
      parameters:
      - in: path
        name: knowledge_id
        required: true
        schema:
          maxLength: 1024
          type: string
      responses:
        "204":
          description: "204"
        default:
          $ref: '#/components/responses/error'
      summary: 删除知识
      tags:
      - knowledge
  /knowledges/update/{knowledge_id}:
    post:
      description: '[magic-box] 更新知识信息'
      operationId: update_knowledge
      parameters:
      - in: path
        name: knowledge_id
        required: true
        schema:
          maxLength: 1024
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/update_knowledge_request'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/knowledge_item'
          description: "200"
        default:
          $ref: '#/components/responses/error'
      summary: 更新知识
      tags:
      - knowledge
  /solutions:
    get:
      description: '[magic-box] 查询方案列表'
      operationId: list_solutions
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/list_solutions_reply'
          description: "200"
        default:
          $ref: '#/components/responses/error'
      summary: 查询方案列表
      tags:
      - solution
    post:
      description: '[magic-box] 创建方案接口'
      operationId: create_solution
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/create_solution_request'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/solution_item'
          description: "200"
        default:
          $ref: '#/components/responses/error'
      summary: 创建方案
      tags:
      - solution
  /solutions/{solution_id}:
    get:
      description: '[magic-box] 查询单个方案'
      operationId: get_solution
      parameters:
      - in: path
        name: solution_id
        required: true
        schema:
          maxLength: 1024
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/solution_item'
          description: "200"
        default:
          $ref: '#/components/responses/error'
      summary: 查询方案详情
      tags:
      - solution
  /solutions/remove/{solution_id}:
    post:
      description: '[magic-box] 删除方案'
      operationId: delete_solution
      parameters:
      - in: path
        name: solution_id
        required: true
        schema:
          maxLength: 1024
          type: string
      responses:
        "204":
          description: "204"
        default:
          $ref: '#/components/responses/error'
      summary: 删除方案
      tags:
      - solution
  /solutions/update/{solution_id}:
    post:
      description: '[magic-box] 更新方案信息'
      operationId: update_solution
      parameters:
      - in: path
        name: solution_id
        required: true
        schema:
          maxLength: 1024
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/update_solution_request'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/solution_item'
          description: "200"
        default:
          $ref: '#/components/responses/error'
      summary: 更新方案
      tags:
      - solution
