/*-----------------------------------------------------------------------------------
 * Kingsoft Office Enterprise Cloud Services.
 * Copyright (c) Kingsoft Office,  All rights reserved.
 *-----------------------------------------------------------------------------------*/
// Code generated by xfx; DO NOT EDIT.

package cmds

import (
	"context"
	"fmt"
	"os"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"

	"ksogit.kingsoft.net/o/xfx/options"
)

var _ = os.Exit
var _ = fmt.Fprintf
var _ pflag.FlagSet
var _ = context.Background
var _ options.Options

type completionZshOptions struct {
	flagSet *pflag.FlagSet
	rootPersistentOptions
}

func unmarshalCompletionZshOptions(flagSet *pflag.FlagSet) *completionZshOptions {
	o := &completionZshOptions{flagSet: flagSet}
	o.LogLevel, _ = flagSet.GetString("log-level")
	return o
}

var completionZshCmd = &cobra.Command{
	Use:   "zsh",
	Short: "Output shell completion code for zsh shell",
	RunE: func(cmd *cobra.Command, args []string) error {
		opts := unmarshalCompletionZshOptions(cmd.Flags())
		return completionZshHandler(context.Background(), args, opts)
	},
}

func init() {
	completionCmd.AddCommand(completionZshCmd)
}
