/*-----------------------------------------------------------------------------------
 * Kingsoft Office Enterprise Cloud Services.
 * Copyright (c) Kingsoft Office,  All rights reserved.
 *-----------------------------------------------------------------------------------*/
// Code generated by xfx; DO NOT EDIT.

package cmds

import (
	"context"
	"fmt"
	"os"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"

	"ksogit.kingsoft.net/o/xfx/options"
)

var _ = os.Exit
var _ = fmt.Fprintf
var _ pflag.FlagSet
var _ = context.Background
var _ options.Options

type completionBashOptions struct {
	flagSet *pflag.FlagSet
	rootPersistentOptions
}

func unmarshalCompletionBashOptions(flagSet *pflag.FlagSet) *completionBashOptions {
	o := &completionBashOptions{flagSet: flagSet}
	o.LogLevel, _ = flagSet.GetString("log-level")
	return o
}

var completionBashCmd = &cobra.Command{
	Use:   "bash",
	Short: "Output shell completion code for bash shell",
	RunE: func(cmd *cobra.Command, args []string) error {
		opts := unmarshalCompletionBashOptions(cmd.Flags())
		return completionBashHandler(context.Background(), args, opts)
	},
}

func init() {
	completionCmd.AddCommand(completionBashCmd)
}
