/*-----------------------------------------------------------------------------------
 * Kingsoft Office Enterprise Cloud Services.
 * Copyright (c) Kingsoft Office,  All rights reserved.
 *-----------------------------------------------------------------------------------*/
// Code generated by xfx; DO NOT EDIT.

package cmds

import (
	"context"
	"os"
)

func completionZshHandler(ctx context.Context, args []string, opts *completionZshOptions) error {
	return rootCmd.GenZshCompletion(os.Stdout)
}
