/*-----------------------------------------------------------------------------------
 * Kingsoft Office Enterprise Cloud Services.
 * Copyright (c) Kingsoft Office,  All rights reserved.
 *-----------------------------------------------------------------------------------*/
// Code generated by xfx; DO NOT EDIT.

package cmds

import (
	"context"
	"os"
)

func completionBashHandler(ctx context.Context, args []string, opts *completionBashOptions) error {
	return rootCmd.GenBashCompletion(os.Stdout)
}
