/*-----------------------------------------------------------------------------------
 * Kingsoft Office Enterprise Cloud Services.
 * Copyright (c) Kingsoft Office,  All rights reserved.
 *-----------------------------------------------------------------------------------*/
// Code generated by xfx; DO NOT EDIT.

package cmds

import (
	"context"
	"fmt"
	"os"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"

	"ksogit.kingsoft.net/o/xfx/options"
)

var _ = os.Exit
var _ = fmt.Fprintf
var _ pflag.FlagSet
var _ = context.Background
var _ options.Options

var completionCmd = &cobra.Command{
	Use:   "completion",
	Short: "Output shell completion code for the specified shell (bash or zsh)",
}

func init() {
	rootCmd.AddCommand(completionCmd)
}
