/*-----------------------------------------------------------------------------------
 * Kingsoft Office Enterprise Cloud Services.
 * Copyright (c) Kingsoft Office,  All rights reserved.
 *-----------------------------------------------------------------------------------*/
// Code generated by xfx; DO NOT EDIT.

package cmds

import (
	"context"
	"fmt"
	"os"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"

	"ksogit.kingsoft.net/o/xfx/options"
)

var _ = os.Exit
var _ = fmt.Fprintf
var _ pflag.FlagSet
var _ = context.Background
var _ options.Options

type rootPersistentOptions struct {
	LogLevel string
}

var rootCmd = &cobra.Command{
	Use: "magic-box",
}

var (
	AppName   = "magic-box"
	Version   = "undefined"
	GitHash   = "undefined"
	BuildTime = "undefined"
	env       = options.NewEnvOptions(AppName)
)

func Execute() {
	if err := rootCmd.Execute(); err != nil {
		os.Exit(-1)
	}
}

func exitOnEnvVarError(key string, err error) {
	fmt.Fprintf(os.Stderr, "Error: invalid environment variable \"%v\": %v)", key, err)
	os.Exit(-1)
}

func init() {
	persistentFlagSet := rootCmd.PersistentFlags()
	persistentFlagSet.SortFlags = false
	persistentFlagSet.StringP(
		"log-level",
		"",
		env.GetString("log-level", "info"),
		"log level",
	)
}
