/*-----------------------------------------------------------------------------------
 * Kingsoft Office Enterprise Cloud Services.
 * Copyright (c) Kingsoft Office,  All rights reserved.
 *-----------------------------------------------------------------------------------*/
// Code generated by xfx; DO NOT EDIT.

package cmds

import (
	"context"
	"fmt"
	"os"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"

	"ksogit.kingsoft.net/o/xfx/options"

	_ "magic-box/context"
)

var _ = os.Exit
var _ = fmt.Fprintf
var _ pflag.FlagSet
var _ = context.Background
var _ options.Options

type serveOptions struct {
	flagSet *pflag.FlagSet
	rootPersistentOptions
}

func unmarshalServeOptions(flagSet *pflag.FlagSet) *serveOptions {
	o := &serveOptions{flagSet: flagSet}
	o.LogLevel, _ = flagSet.GetString("log-level")
	return o
}

var serveCmd = &cobra.Command{
	Use:   "serve",
	Short: "Starting public APIs and private APIs",
	RunE: func(cmd *cobra.Command, args []string) error {
		opts := unmarshalServeOptions(cmd.Flags())
		return serveHandler(context.Background(), args, opts)
	},
}

func init() {
	rootCmd.AddCommand(serveCmd)
}
