/*-----------------------------------------------------------------------------------
 * Kingsoft Office Enterprise Cloud Services.
 * Copyright (c) Kingsoft Office,  All rights reserved.
 *-----------------------------------------------------------------------------------*/
// Code generated by xfx; DO NOT EDIT.

package cmds

import (
	"context"
	"fmt"
)

func versionHandler(ctx context.Context, args []string, opts *versionOptions) error {
	fmt.Printf("Version:    %s\n", Version)
	fmt.Printf("Git Hash:   %s\n", GitHash)
	fmt.Printf("Build Time: %s\n", BuildTime)
	return nil
}
