/*-----------------------------------------------------------------------------------
 * Kingsoft Office Enterprise Cloud Services.
 * Copyright (c) Kingsoft Office,  All rights reserved.
 *-----------------------------------------------------------------------------------*/
// Code generated by xfx; DO NOT EDIT.

package cmds

import (
	"context"
	"fmt"
	"os"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"

	"ksogit.kingsoft.net/o/xfx/options"
)

var _ = os.Exit
var _ = fmt.Fprintf
var _ pflag.FlagSet
var _ = context.Background
var _ options.Options

type versionOptions struct {
	flagSet *pflag.FlagSet
	rootPersistentOptions
}

func unmarshalVersionOptions(flagSet *pflag.FlagSet) *versionOptions {
	o := &versionOptions{flagSet: flagSet}
	o.LogLevel, _ = flagSet.GetString("log-level")
	return o
}

var versionCmd = &cobra.Command{
	Use:   "version",
	Short: "Display this binary's build time and git hash of this build",
	RunE: func(cmd *cobra.Command, args []string) error {
		opts := unmarshalVersionOptions(cmd.Flags())
		return versionHandler(context.Background(), args, opts)
	},
}

func init() {
	rootCmd.AddCommand(versionCmd)
}
