#!/bin/bash
# Code generated by xfx; DO NOT EDIT.

wd=$(pwd)

go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.49.0

lintpath=/tmp/devops-tools

if ! test -d $lintpath ; then
    git clone git@ksogit.kingsoft.net:encs/devops-tools.git $lintpath
fi

cd $lintpath && git checkout . && git checkout master && git pull origin master
cd $lintpath/linter && make build-plugin

cd $wd
cp $lintpath/code-scan-tool/.golangci.yml .
cp $lintpath/linter/cmd/wpsplus-lint.so .
golangci-lint run --max-same-issues=0 --max-issues-per-linter=0 ./...
rm .golangci.yml wpsplus-lint.so
