#!/bin/bash
# Code generated by xfx; DO NOT EDIT.

wd=$(pwd)

go install github.com/reviewdog/reviewdog/cmd/reviewdog@v0.13.0
go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.49.0

lintpath=/tmp/devops-tools

if ! test -d $lintpath ; then
    git clone git@ksogit.kingsoft.net:encs/devops-tools.git $lintpath
fi

cd $lintpath && git checkout . && git checkout master && git pull origin master
cd $lintpath/linter && make build-plugin

cd $wd
cp $lintpath/code-scan-tool/.golangci.yml .
cp $lintpath/code-scan-tool/.reviewdog.yml .
cp $lintpath/linter/cmd/wpsplus-lint.so .
reviewdog -reporter=local --diff="git diff master" -runners=golangci-lint -filter-mode=added
rm .golangci.yml .reviewdog.yml wpsplus-lint.so
