#!/bin/bash
# Code generated by xfx; DO NOT EDIT.

stage_revision=v2.12.31
stage_path=/tmp/stage/$stage_revision
stage_file=$stage_path/stage
GOARCH='' GOBIN=$stage_path go install ksogit.kingsoft.net/o/stage/v2@$stage_revision

wd=$(pwd)

echo "gen $wd"
$stage_file pullspec
$stage_file gen "$@"
