#!/bin/bash
# Code generated by xfx; DO NOT EDIT.

pkg=$(go list)
wd=$(pwd)
sdks="$(find ./sdk -type d ! -path ./sdk)"
for dir in $sdks; do
	if [[ ! -f "$dir/sdk.go" ]]; then
		continue
	fi

	dir="${dir#"./sdk/"}"
	srcModified=$(date -r ./sdk/$dir/sdk.go +%Y%m%d%H%M.%S | tr -d "\n")
	destModified="0"
	if [[ -f "./mock/$dir/mock.go" ]]; then
		destModified=$(date -r ./mock/$dir/mock.go +%Y%m%d%H%M.%S | tr -d "\n")
	fi
	if [ "$srcModified" == "$destModified" ]; then
		echo "sdk unchanged, skip gen sdk mock to ./mock/$dir/mock.go"
		continue
	fi

	echo "gen $(basename $dir) mock to ./mock/$dir/mock.go"
	mkdir -p ./mock/$dir
	mockgen \
		-package $(basename $dir | sed -e "s/-//g")mock \
		-source=./sdk/$dir/sdk.go \
		-aux_files=$pkg/sdk/$dir=./sdk/$dir/sdk_ex.go \
		-destination ./mock/$dir/mock.go &
done

if [[ -d "./biz" ]]; then
    bizs=$(grep  -E "type +[A-Za-z0-9]+ +interface" --exclude "*_test.go" --exclude "*_mock.go" ./biz/*.go | awk -F: '{print $1}')
	for file in $bizs; do
		mockFile="./biz/$(basename $file .go)_mock.go"
		srcModified=$(date -r $file +%Y%m%d%H%M.%S | tr -d "\n")
		destModified="0"
		if [[ -f "$mockFile" ]]; then
			destModified=$(date -r $mockFile +%Y%m%d%H%M.%S | tr -d "\n")
		fi
		if [ "$srcModified" == "$destModified" ]; then
			echo "repo unchanged, skip gen repo mock to $mockFile"
			continue
		fi

		echo "gen repo mock to $mockFile"
		mockgen \
			-package biz \
			-source=$file \
			-destination $mockFile &
	done
fi



echo "gen xfx mock to ./mock/xfx/mock.go"
mkdir -p $wd/mock/xfx
mockgen -package xfxmock ksogit.kingsoft.net/o/xfx App > $wd/mock/xfx/mock.go &

wait

for dir in $sdks; do
	if [[ ! -f "$dir/sdk.go" ]]; then
		continue
	fi

	dir="${dir#"./sdk/"}"
	srcModified=$(date -r ./sdk/$dir/sdk.go +%Y%m%d%H%M.%S | tr -d "\n")
	touch -a -m -t "$srcModified" "./mock/$dir/mock.go"
done

if [[ -d "./biz" ]]; then
    bizs=$(grep  -E "type +[A-Za-z0-9]+ +interface" --exclude "*_test.go" --exclude "*_mock.go" ./biz/*.go | awk -F: '{print $1}')
	for file in $bizs; do
		mockFile="./biz/$(basename $file .go)_mock.go"
		srcModified=$(date -r $file +%Y%m%d%H%M.%S | tr -d "\n")
		touch -a -m -t "$srcModified" "$mockFile"
	done
fi

echo "gen mock done"
