#!/bin/bash
# Code generated by xfx; DO NOT EDIT.

stage_revision=v2.12.31
stage_path=/tmp/stage/$stage_revision
stage_file=$stage_path/stage
GOARCH='' GOBIN=$stage_path go install ksogit.kingsoft.net/o/stage/v2@$stage_revision

wd=$(pwd)

pro_name=$(grep "ENV PROJECT_NAME" $wd/Dockerfile | tail -n 1 | awk -F '=' '{print $2}')
if [ ! -n "$1" ]; then
  branch_name=$(git branch | sed -n '/\* /s///p')
else
  branch_name=$1
fi
if [ -z "$branch_name" ]; then
    branch_name="beta"
fi

$stage_file i18n pull --pro $pro_name --branch $branch_name --fx=xfx

