/*-----------------------------------------------------------------------------------
 * Kingsoft Office Enterprise Cloud Services.
 * Copyright (c) Kingsoft Office,  All rights reserved.
 *-----------------------------------------------------------------------------------*/
// Code generated by xfx; DO NOT EDIT.

package ep

import (
	"net/http"

	"ksogit.kingsoft.net/o/xfx"
	"ksogit.kingsoft.net/o/xfx/el"
	"ksogit.kingsoft.net/o/xfx/endpoint"
	"ksogit.kingsoft.net/o/xfx/rw"

	ctx "magic-box/context"
	srv "magic-box/services"
)

type CreateSolution struct {
	xfx.EndpointBase
}

func (h *CreateSolution) Name() string {
	return "CreateSolution"
}

func (h *CreateSolution) Method() string {
	return "POST"
}

func (h *CreateSolution) URL() string {
	return "/solutions"
}

func parseCreateSolutionRequest(w http.ResponseWriter, r *http.Request) (*srv.CreateSolutionRequest, error) {
	var err error
	_ = err
	in := srv.NewCreateSolutionRequest()
	err = rw.ReadObject(w, r, in)
	if err != nil {
		return nil, el.Adapt(err)
	}
	return in, nil
}

func (h *CreateSolution) Endpoint(app xfx.App) endpoint.Endpoint {
	callService := srv.NewCreateSolutionService(ctx.Get(app))
	return func(w http.ResponseWriter, r *http.Request) error {
		in, err := parseCreateSolutionRequest(w, r)
		if err != nil {
			return rw.WriteError(w, r, el.Adapt(err))
		}
		in.EscapeStrings()
		out, err := callService(r.Context(), in)
		if err != nil {
			return rw.WriteError(w, r, err)
		}
		return rw.WriteJson(w, 200, out)
	}
}

func init() {
	xfx.RegisterEndpoint(xfx.PUBLIC, &CreateSolution{})
}
