/*-----------------------------------------------------------------------------------
 * Kingsoft Office Enterprise Cloud Services.
 * Copyright (c) Kingsoft Office,  All rights reserved.
 *-----------------------------------------------------------------------------------*/
// Code generated by xfx; DO NOT EDIT.

package ep

import (
	"net/http"

	"ksogit.kingsoft.net/o/xfx"
	"ksogit.kingsoft.net/o/xfx/el"
	"ksogit.kingsoft.net/o/xfx/endpoint"
	"ksogit.kingsoft.net/o/xfx/rw"

	ctx "magic-box/context"
	srv "magic-box/services"
)

type DeleteAssistant struct {
	xfx.EndpointBase
}

func (h *DeleteAssistant) Name() string {
	return "DeleteAssistant"
}

func (h *DeleteAssistant) Method() string {
	return "POST"
}

func (h *DeleteAssistant) URL() string {
	return "/assistants/remove/{assistant_id}"
}

func parseDeleteAssistantRequest(w http.ResponseWriter, r *http.Request) (*srv.DeleteAssistantRequest, error) {
	var err error
	_ = err
	in := srv.NewDeleteAssistantRequest()
	err = rw.ParsePath(r, in)
	if err != nil {
		return nil, el.Adapt(err)
	}
	return in, nil
}

func (h *DeleteAssistant) Endpoint(app xfx.App) endpoint.Endpoint {
	callService := srv.NewDeleteAssistantService(ctx.Get(app))
	return func(w http.ResponseWriter, r *http.Request) error {
		in, err := parseDeleteAssistantRequest(w, r)
		if err != nil {
			return rw.WriteError(w, r, el.Adapt(err))
		}
		in.EscapeStrings()
		err = callService(r.Context(), in)
		if err != nil {
			return rw.WriteError(w, r, err)
		}
		return rw.WriteStatus(w, 204)
	}
}

func init() {
	xfx.RegisterEndpoint(xfx.PUBLIC, &DeleteAssistant{})
}
