/*-----------------------------------------------------------------------------------
 * Kingsoft Office Enterprise Cloud Services.
 * Copyright (c) Kingsoft Office,  All rights reserved.
 *-----------------------------------------------------------------------------------*/
// Code generated by xfx; DO NOT EDIT.

package ep

import (
	"net/http"

	"ksogit.kingsoft.net/o/xfx"
	"ksogit.kingsoft.net/o/xfx/el"
	"ksogit.kingsoft.net/o/xfx/endpoint"
	"ksogit.kingsoft.net/o/xfx/rw"

	ctx "magic-box/context"
	srv "magic-box/services"
)

type GetKnowledge struct {
	xfx.EndpointBase
}

func (h *GetKnowledge) Name() string {
	return "GetKnowledge"
}

func (h *GetKnowledge) Method() string {
	return "GET"
}

func (h *GetKnowledge) URL() string {
	return "/knowledges/{knowledge_id}"
}

func parseGetKnowledgeRequest(w http.ResponseWriter, r *http.Request) (*srv.GetKnowledgeRequest, error) {
	var err error
	_ = err
	in := srv.NewGetKnowledgeRequest()
	err = rw.ParsePath(r, in)
	if err != nil {
		return nil, el.Adapt(err)
	}
	return in, nil
}

func (h *GetKnowledge) Endpoint(app xfx.App) endpoint.Endpoint {
	callService := srv.NewGetKnowledgeService(ctx.Get(app))
	return func(w http.ResponseWriter, r *http.Request) error {
		in, err := parseGetKnowledgeRequest(w, r)
		if err != nil {
			return rw.WriteError(w, r, el.Adapt(err))
		}
		in.EscapeStrings()
		out, err := callService(r.Context(), in)
		if err != nil {
			return rw.WriteError(w, r, err)
		}
		return rw.WriteJson(w, 200, out)
	}
}

func init() {
	xfx.RegisterEndpoint(xfx.PUBLIC, &GetKnowledge{})
}
