/*-----------------------------------------------------------------------------------
 * Kingsoft Office Enterprise Cloud Services.
 * Copyright (c) Kingsoft Office,  All rights reserved.
 *-----------------------------------------------------------------------------------*/
// Code generated by xfx; DO NOT EDIT.

package ep

import (
	"net/http"

	"ksogit.kingsoft.net/o/xfx"
	"ksogit.kingsoft.net/o/xfx/el"
	"ksogit.kingsoft.net/o/xfx/endpoint"
	"ksogit.kingsoft.net/o/xfx/rw"

	ctx "magic-box/context"
	srv "magic-box/services"
)

type ListAis struct {
	xfx.EndpointBase
}

func (h *ListAis) Name() string {
	return "ListAis"
}

func (h *ListAis) Method() string {
	return "GET"
}

func (h *ListAis) URL() string {
	return "/ais"
}

func parseListAisRequest(w http.ResponseWriter, r *http.Request) (*srv.ListAisRequest, error) {
	var err error
	_ = err
	in := srv.NewListAisRequest()
	return in, nil
}

func (h *ListAis) Endpoint(app xfx.App) endpoint.Endpoint {
	callService := srv.NewListAisService(ctx.Get(app))
	return func(w http.ResponseWriter, r *http.Request) error {
		in, err := parseListAisRequest(w, r)
		if err != nil {
			return rw.WriteError(w, r, el.Adapt(err))
		}
		in.EscapeStrings()
		out, err := callService(r.Context(), in)
		if err != nil {
			return rw.WriteError(w, r, err)
		}
		return rw.WriteJson(w, 200, out)
	}
}

func init() {
	xfx.RegisterEndpoint(xfx.PUBLIC, &ListAis{})
}
