/*-----------------------------------------------------------------------------------
 * Kingsoft Office Enterprise Cloud Services.
 * Copyright (c) Kingsoft Office,  All rights reserved.
 *-----------------------------------------------------------------------------------*/
// Code generated by xfx; DO NOT EDIT.

package schemas

import (
	"html"
	"time"

	"ksogit.kingsoft.net/o/xfx/validator"
)

var _ = time.Parse
var _ = html.EscapeString
var _ = validator.CheckRequired

type CreateSolutionRequest struct {
	Description string `json:"description" validate:"max=1024"`
	Name        string `json:"name" validate:"max=1024"`
}

func NewCreateSolutionRequest() CreateSolutionRequest {
	v := CreateSolutionRequest{}
	return v
}

func (s *CreateSolutionRequest) EscapeStrings() {
	s.Description = html.EscapeString(s.Description)
	s.Name = html.EscapeString(s.Name)
}

func (CreateSolutionRequest) JSONFields(fields []string) error {
	check := map[string]bool{
		"description": false,
		"name":        false,
	}
	err := validator.CheckRequired(check, fields)
	if err != nil {
		return err
	}
	return nil
}
