/*-----------------------------------------------------------------------------------
 * Kingsoft Office Enterprise Cloud Services.
 * Copyright (c) Kingsoft Office,  All rights reserved.
 *-----------------------------------------------------------------------------------*/
// Code generated by xfx; DO NOT EDIT.

package schemas

import (
	"html"
	"time"

	"ksogit.kingsoft.net/o/xfx/validator"
)

var _ = time.Parse
var _ = html.EscapeString
var _ = validator.CheckRequired

type Error struct {
	Code ErrorCode `json:"code"`
	More *Error    `json:"more,omitempty"`
	Msg  string    `json:"msg"`
}

func NewError() Error {
	v := Error{}
	return v
}

func (s *Error) EscapeStrings() {
	s.Msg = html.EscapeString(s.Msg)
}

func (Error) JSONFields(fields []string) error {
	check := map[string]bool{
		"code": false,
		"msg":  false,
	}
	err := validator.CheckRequired(check, fields)
	if err != nil {
		return err
	}
	return nil
}
