/*-----------------------------------------------------------------------------------
 * Kingsoft Office Enterprise Cloud Services.
 * Copyright (c) Kingsoft Office,  All rights reserved.
 *-----------------------------------------------------------------------------------*/
// Code generated by xfx; DO NOT EDIT.

package schemas

import (
	"fmt"
)

type ErrorCode int

const (
	_ ErrorCode = iota

	ErrorCodeCodeParamFormatError = 40000002
)

func (t ErrorCode) MarshalJSON() ([]byte, error) {
	switch t {
	case ErrorCodeCodeParamFormatError:
		return []byte(`40000002`), nil
	}
	return nil, fmt.Errorf("invalid error_code: %v", t)
}

func (t *ErrorCode) UnmarshalJSON(data []byte) error {
	text := string(data)
	switch text {
	case `40000002`:
		*t = ErrorCodeCodeParamFormatError
		return nil
	}
	return fmt.Errorf("invalid error_code: %v", text)
}

func (t ErrorCode) MarshalText() ([]byte, error) {
	switch t {
	case ErrorCodeCodeParamFormatError:
		return []byte(`40000002`), nil
	}
	return nil, fmt.Errorf("invalid error_code: %v", t)
}

func (t *ErrorCode) UnmarshalText(data []byte) error {
	text := string(data)
	switch text {
	case `40000002`:
		*t = ErrorCodeCodeParamFormatError
		return nil
	}
	return fmt.Errorf("invalid error_code: %v", text)
}

func (t ErrorCode) String() string {
	switch t {
	case ErrorCodeCodeParamFormatError:
		return `40000002`
	}
	return ""
}
