/*-----------------------------------------------------------------------------------
 * Kingsoft Office Enterprise Cloud Services.
 * Copyright (c) Kingsoft Office,  All rights reserved.
 *-----------------------------------------------------------------------------------*/
// Code generated by xfx; DO NOT EDIT.

package schemas

import (
	"html"
	"time"

	"ksogit.kingsoft.net/o/xfx/validator"
)

var _ = time.Parse
var _ = html.EscapeString
var _ = validator.CheckRequired

type HealthReply struct {
	Message string `json:"message" validate:"max=1024"`
	Status  string `json:"status" validate:"max=1024"`
	Version string `json:"version" validate:"max=1024"`
}

func NewHealthReply() HealthReply {
	v := HealthReply{}
	return v
}

func (s *HealthReply) EscapeStrings() {
	s.Message = html.EscapeString(s.Message)
	s.Status = html.EscapeString(s.Status)
	s.Version = html.EscapeString(s.Version)
}

func (HealthReply) JSONFields(fields []string) error {
	check := map[string]bool{
		"message": false,
		"status":  false,
		"version": false,
	}
	err := validator.CheckRequired(check, fields)
	if err != nil {
		return err
	}
	return nil
}
