/*-----------------------------------------------------------------------------------
 * Kingsoft Office Enterprise Cloud Services.
 * Copyright (c) Kingsoft Office,  All rights reserved.
 *-----------------------------------------------------------------------------------*/
// Code generated by xfx; DO NOT EDIT.

package schemas

import (
	"html"
	"time"

	"ksogit.kingsoft.net/o/xfx/validator"
)

var _ = time.Parse
var _ = html.EscapeString
var _ = validator.CheckRequired

type ListAssistantsReply struct {
	Items []AssistantItem `json:"items" validate:"max=1024,dive"`
	Total int             `json:"total"`
}

func NewListAssistantsReply() ListAssistantsReply {
	v := ListAssistantsReply{}
	return v
}

func (s *ListAssistantsReply) EscapeStrings() {
	for i := range s.Items {
		s.Items[i].EscapeStrings()
	}
}

func (ListAssistantsReply) JSONFields(fields []string) error {
	check := map[string]bool{
		"items": false,
		"total": false,
	}
	err := validator.CheckRequired(check, fields)
	if err != nil {
		return err
	}
	return nil
}
