/*-----------------------------------------------------------------------------------
 * Kingsoft Office Enterprise Cloud Services.
 * Copyright (c) Kingsoft Office,  All rights reserved.
 *-----------------------------------------------------------------------------------*/
// Code generated by xfx; DO NOT EDIT.

package schemas

import (
	"html"
	"time"

	"ksogit.kingsoft.net/o/xfx/validator"
)

var _ = time.Parse
var _ = html.EscapeString
var _ = validator.CheckRequired

type SolutionItem struct {
	CreatedAt   string `json:"created_at" validate:"max=1024"`
	Description string `json:"description" validate:"max=1024"`
	Id          string `json:"id" validate:"max=1024"`
	Name        string `json:"name" validate:"max=1024"`
	UpdatedAt   string `json:"updated_at" validate:"max=1024"`
}

func NewSolutionItem() SolutionItem {
	v := SolutionItem{}
	return v
}

func (s *SolutionItem) EscapeStrings() {
	s.CreatedAt = html.EscapeString(s.CreatedAt)
	s.Description = html.EscapeString(s.Description)
	s.Id = html.EscapeString(s.Id)
	s.Name = html.EscapeString(s.Name)
	s.UpdatedAt = html.EscapeString(s.UpdatedAt)
}

func (SolutionItem) JSONFields(fields []string) error {
	check := map[string]bool{
		"created_at":  false,
		"description": false,
		"id":          false,
		"name":        false,
		"updated_at":  false,
	}
	err := validator.CheckRequired(check, fields)
	if err != nil {
		return err
	}
	return nil
}
