/*-----------------------------------------------------------------------------------
 * Kingsoft Office Enterprise Cloud Services.
 * Copyright (c) Kingsoft Office,  All rights reserved.
 *-----------------------------------------------------------------------------------*/
// Code generated by xfx; DO NOT EDIT.

package schemas

import (
	"html"
	"time"

	"ksogit.kingsoft.net/o/xfx/validator"
)

var _ = time.Parse
var _ = html.EscapeString
var _ = validator.CheckRequired

type UpdateAiRequest struct {
	Description string `json:"description" validate:"max=1024"`
	Name        string `json:"name" validate:"max=1024"`
}

func NewUpdateAiRequest() UpdateAiRequest {
	v := UpdateAiRequest{}
	return v
}

func (s *UpdateAiRequest) EscapeStrings() {
	s.Description = html.EscapeString(s.Description)
	s.Name = html.EscapeString(s.Name)
}

func (UpdateAiRequest) JSONFields(fields []string) error {
	check := map[string]bool{
		"description": false,
		"name":        false,
	}
	err := validator.CheckRequired(check, fields)
	if err != nil {
		return err
	}
	return nil
}
